UPDATE public.employees SET status='Inactive' WHERE employee_id='00000000';
UPDATE public.employees SET status='Inactive' WHERE employee_id='77140142';
UPDATE public.employees SET status='Inactive' WHERE employee_id='77140001';
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141108', 'Aashish Kajla', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140564', 'Aashita Prajapati', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140944', 'Abhishek', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141058', 'Abhishek', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141331', 'Abhishek Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140781', 'Akanksha Sharma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141412', 'Akul Tomar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141286', 'Aman Nagar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141287', 'Aman Yadav', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140609', 'Anchal Sharma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140975', 'Anha Saifi', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140946', 'Anil Kumar Singh', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140380', 'Anjali Chandaliya', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140765', 'Ankush', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141403', 'Anshu', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141407', 'Anushka Tyagi', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141055', 'Arpit Kumar Arya', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141414', 'Arsh Atiq Khan', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141405', 'Arti Shukla', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140947', 'Ashwini Kumari', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141057', 'Ayush Garg', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140558', 'Badal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140948', 'Bhavna', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140949', 'Bhavya Dixit', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140950', 'Chanchal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141092', 'Chetna Tyagi', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140951', 'Chiranjeev Vats', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140952', 'Deepak Pachauri', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140788', 'Deepanshu', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140787', 'Dev kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140974', 'Fiza Rani', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141340', 'Gaurav Kumar Verma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140953', 'Gautam', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140954', 'Himanshu Panchal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141056', 'Ishika', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140955', 'Jyoti Kumari', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140956', 'Kamal Kant', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141146', 'Khushal Kumar Varun', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140957', 'Khushi', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140958', 'Laxmi', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140959', 'Lokesh kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141199', 'Manish Kashyap', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140783', 'Manisha', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141413', 'Manya', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140785', 'Megha Verma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140466', 'Mohit Bhardwaj', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140658', 'Monika Singh', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141404', 'Mrityunjay Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141410', 'Neha', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141415', 'Nidhi Tyagi', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141349', 'Nikhil Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140799', 'Nishant pal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141303', 'Nitin', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141304', 'Nitin Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141030', 'Nitin pal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141408', 'Pooja', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140370', 'Pooja Taliyan', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141406', 'Poonam Singh', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140385', 'Poonam Verma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141352', 'Pratik', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141062', 'Priyanka', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141201', 'Pulkit Mittal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140962', 'Puneet kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140960', 'Rahul kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140961', 'Ranjana', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141063', 'Riya', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141409', 'Riya Yadav', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141355', 'Rohit', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141311', 'Rohit Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140812', 'Ruby', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140963', 'Sagar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140377', 'Sakshi Choudhary', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140973', 'Salmani Nida Noor', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140964', 'Sharvan Agarwal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140965', 'Shikha Kumari', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140702', 'Shriram', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141059', 'Shubham Tomar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140966', 'Shubham Yadav', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141211', 'Shubhanshu', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140784', 'Shweta', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141402', 'Shyna', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140800', 'Simran', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140801', 'Soorab Yadav', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140968', 'Sorabh kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140969', 'Subhansu', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140786', 'Sunny', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141064', 'Tarun Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140789', 'Tarun Sharma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140421', 'Umesh Giri', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140971', 'Upasana Aggarwal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141411', 'Vandana', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141323', 'Veni Madhav', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141401', 'Vidhi Sharma', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77141361', 'Vikramjeet Singh', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140403', 'Vinay Kumar', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140972', 'Vishal', 'Train Attendant', 'Train Operations', 'Active', 'employee');
INSERT INTO public.employees (employee_id, name, designation, department, status, role) VALUES ('77140351', 'Vishwas', 'Train Attendant', 'Train Operations', 'Active', 'employee');